### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by yoonjiyong** [TykanN/kpostal#1]
고맙습니다. 

kopo 패키지 404 뜨는 거 보고 깜짝 놀라서 대처 할려고 했는데 바로 이렇게 패키지가 있어서 시간을 많이 절약했습니다.
👏👏

고마움을 표현하기 위해 쓴 issue 임으로 추후 삭제하겠습니다.

**Comment by TykanN** [comment]
@yoonjiyong 
감사합니다! 저도 서비스 중인 프로젝트에서 해당 에러때문에 문제를 겪어서 따로 패키징했네요.

동일한 이슈 가능성에 대비해서 앱 내 로컬 서버를 이용한 검색페이지 호스팅도 구현해놓았으니 고려해보셔도 좋을겁니다. 🙏
