### ISSUE TITLE
ios 에서 일부 주소의 좌표값이 null로 반환됨 

### ISSUE THREAD

**Issue by Daniel-JinwooLee** [TykanN/kpostal#11]
안녕하세요 개발자님
kpostal  잘 이용하고 있습니다, 다만
ios 에서 특정 주소들 ( 예: 독산로 169)의 위치가 
lat, long, kakaolat, kakaolong 모두 null 로 reply 되는 문제를 발견하였습니다.
이것에 대해서 확인해주시면 정말 감사하겠습니다.

**Comment by TykanN** [comment]
안녕하세요
@Daniel-JinwooLee 님!

기존 영문 주소 기준으로 지오코딩 서비스를 이용했습니다.
영문 주소로 조회 실패 시, 국문 주소로 재차 조회하도록 서비스 로직을 변경했습니다.
해당 내용을 반영한 0.5.0 버전으로 업데이트 해주시면 됩니다.

이슈 상 언급해주신 "독산로 169"에 대해서는 정상적으로 확인했습니다.
하지만 경위도 값은 외부에 의존하는 기능으로 조회 상 없는 경우에는 패키지 수준에서 해결할 수 없습니다.

카카오 경위도는 카카오에서 주는 값을 그대로 전달하는 것으로 문제 없는 것으로 확인됩니다.
null이 오는 경우 카카오 개발자 환경 설정(특히 도메인 부분)에 문제가 있을 가능성이 크므로 확인 부탁드립니다.

카카오 경위도 또한 특정 주소에 따라 null이 오는 경우, 해당 주소와 함께 이슈 repoen해주시면 체크해보겠습니다.

**Comment by Daniel-JinwooLee** [comment]
감사합니다 !! 😆
