### ISSUE TITLE
간혹 지번 주소가 안 넘어오는 이슈

### ISSUE THREAD

**Issue by yoonjiyong** [TykanN/kpostal#12]
안녕하세요 

Webview에서는 도로명 , 지번 주소가 모두 나오지만 
도로명 주소를 터치하면 지번주소가 return 값으로 들어오지 않는 이슈가 있습니다. 
( 지번 주소를 터치하면 나옵니다 ) 

예를 들어 
< 서울 종로구 낙산성곽길 4 >

웹뷰
![photo_2022-07-29 11 27 12](https://user-images.githubusercontent.com/68573852/181670068-4dac5883-b103-41ed-8f9e-a86146aa8f40.jpeg)

리턴
![photo_2022-07-29 11 26 05](https://user-images.githubusercontent.com/68573852/181669944-aff1a5cf-7985-4104-9201-c1b00d7d43f4.jpeg)

**Comment by TykanN** [comment]
안녕하세요!

해당 도로명 주소(낙산성곽길 4)에 해당하는 지번 주소가 다수(4개) 존재해서 지번 주소를 특정하지 않아 생기는 문제로 확인됩니다.

매핑되는 지번 주소가 다수 존재하는 경우, '더보기' 위에 노출되는 대표 지번 주소가 매핑되어 전달되도록 할 수 있겠네요.
수정하여 반영된 버전이 배포되면 코멘트 추가로 남겨드리겠습니다. 이슈 제보 감사합니다 👍

**Comment by TykanN** [comment]
https://github.com/TykanN/kpostal/commit/f4c8390005878dc556409241e20c6f9b2c6c1586 해당 커밋과 함께 배포되었습니다.

v0.5.1로 업데이트하시면 됩니다 :)

**Comment by yoonjiyong** [comment]
한글로 이슈를 남기고 ,
그 이슈가 수정되어 몇시간안에 배포되는 경험을 해보네요 허허

잘 됩니다 👍
