### ISSUE TITLE
Android target SDK 33 설정시 InAppWebView version 오류

### ISSUE THREAD

**Issue by yoonjiyong** [TykanN/kpostal#14]
안녕하세요

https://pub.dev/packages/flutter_local_notifications

Local notifications 구현을 위해 안드로이드 compile SDK 를 33으로 설정하니 , 
inAppWebView 버젼이 호환이 안됩니다.

**Comment by yoonjiyong** [comment]
> 안녕하세요
> 
> https://pub.dev/packages/flutter_local_notifications
> 
> Local notifications 구현을 위해 안드로이드 compile SDK 를 33으로 설정하니 , inAppWebView 버젼이 호환이 안됩니다.

**Comment by TykanN** [comment]
Inappwebview의 stable 버전이 안드로이드 컴파일sdk 33 버전을 지원하지 않습니다.
해당 패키지에서 빠른 대응을 기대하기 다소 어려워 보입니다.

이슈가 해결되기 전까지
1. 해당 부분이 수정된 포크 버전을 override 하시거나
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1223#issuecomment-1193897965
2. 문제가 되는 flutter_local_notifitications 의 버전을 낮추시길 바랍니다.
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1269#issuecomment-1225998308

**Comment by yoonjiyong** [comment]
https://pub.dev/packages/flutter_inappwebview

선생님 올 것이 왔습니다

**Comment by TykanN** [comment]
Inappwebview 6.x.x. 버전에서 안드로이드 SDK 33에 대한 대응이 가능하여
해당 버전을 적용한 pre-release 버전을 pub.dev에서 사용 가능합니다.

https://pub.dev/packages/kpostal/versions/1.0.0-dev.1
