### ISSUE TITLE
좌표 반환 값 오류

### ISSUE THREAD

**Issue by jinsyu** [TykanN/kpostal#16]
좌표 반환 값이 너무 쌩뚱맞은 곳으로 나오는 경우가 있습니다.

https://dapi.kakao.com/v2/local/search/address.json?query

api를 이용해서 정확한 lat, lng 반환 해주실 수 있을까요?

바쁘시다면 제가 PR날리도록 하겠습니다.

**Comment by TykanN** [comment]
어떤 상황에서 위경도 좌표가 맞지 않게 나오는지 설명 부탁드려도 될까요? (네이티브 or 카카오 지오코딩, 해당 주소명 등)

기본적으로 네이티브 지오코딩을 이용하며, 카카오 맵 API를 이용한 방식은 옵션으로 포함되어 있습니다.
언급해주신 카카오 로컬 API 역시 옵션으로는 제공될 수 있으나, 맵 API와 서로 다른 좌표가 나오는지 확인이 필요합니다.

**Comment by TykanN** [comment]
추가적인 진행이 필요한 경우 reopen 해주세요! 👍
