### ISSUE TITLE
ios 콜백오류 

### ISSUE THREAD

**Issue by gamcho3** [TykanN/kpostal#17]
이전 이슈처럼 주소 클릭시 하얀화면에서 넘어가지않는 오류가 있습니다. 안드로이드에선 시뮬레이터로 구동 확인했습니다.

**Comment by marsg6Fiet** [comment]
ios 15.6.1에서 동일 현상이 발생하며, 다음과 같은 로그가 출력됩니다. flutter_inappwebview 패키지 repo에도 동일한 issue가 예전부터 상당수 올라와 있는 것으로 확인되지만, 실제로 해결에 대한 답변은 찾기가 어렵네요.
Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service

**Comment by TykanN** [comment]
@gamcho3 @marsg6Fiet 
iOS 15.6.1 버전 외에 콜백 오류가 발생하는 환경에 대해 추가적으로 확인 가능하실까요?
- 사용한 kpostal 패키지 버전
- 모든 주소 검색 시 or 특정 주소 검색 시 (특정 주소라면 해당 주소)

업무 일정 관계로 빠른 대응이 어렵습니다. 혹시 제가 업데이트 하기 전에 해결하시는 경우 PR 올려주셔도 됩니다.

**Comment by marsg6Fiet** [comment]
> 

버전은 0.5.1이었고, 모든 주소 검색에 대해서 발생했습니다.
일단 테스트해본 모든 ios 기기에서 주소를 검색하고 나서, 주소를 선택했을 때 callback이 오지 않고 하얀 화면이 뜨며 해당 로그가 출력됐습니다.

**Comment by marsg6Fiet** [comment]
> @gamcho3 @marsg6Fiet iOS 15.6.1 버전 외에 콜백 오류가 발생하는 환경에 대해 추가적으로 확인 가능하실까요?
> 
> * 사용한 kpostal 패키지 버전
> * 모든 주소 검색 시 or 특정 주소 검색 시 (특정 주소라면 해당 주소)
> 
> 업무 일정 관계로 빠른 대응이 어렵습니다. 혹시 제가 업데이트 하기 전에 해결하시는 경우 PR 올려주셔도 됩니다.

버전은 0.5.1이었고, 검색해본 모든 주소 검색에 대해서 발생했습니다.
일단 테스트해본 모든 ios 기기에서 주소를 검색하고 나서, 주소를 선택했을 때 callback이 오지 않고 하얀 화면이 뜨며 해당 로그가 출력됐습니다.

**Comment by TykanN** [comment]
kpostal 0.5.1 기준으로 iOS 테스트해본 결과 해당 이슈를 확인할 수 없습니다.
테스트 환경도 첨부드립니다. 패키지 내 example 기준으로 테스트했습니다.

reproducible example이 필요합니다.
- 해당 에러를 reproduce 할 수 있는 간단한 코드 예제 repo
- 실기기, 시뮬레이터 중 특정 환경인지 여부
- iOS 특정 버전 문제인지 여부

에러 메세지처럼 iOS 웹킷 쪽 문제면 관련되는게 로컬서버 사용 시 http 통신 허용 설정이 가장 연관되지만,
해당 부분 설정이 안 된거라면 주소 검색 페이지도 열리지 않아야 하므로 아닐 듯 합니다.

우선 prerelease된 1.0.0 버전도 있습니다. inappwebview 버전이 6.x.x으로 올라간 버전입니다.
v0.5.1에서도 해당 에러를 발견할 수 없어서, 해결책이 될 수 있을지는 확인 불가능합니다.
https://pub.dev/packages/kpostal/versions/1.0.0-dev.1 

본 이슈에 대한 더 구체적인 정보가 제공되기 전까지는 중단합니다.

---
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.6 21G115 darwin-arm, locale ko-KR)
    • Flutter version 3.3.10 on channel stable at /Users/tykan/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 135454af32 (2 weeks ago), 2022-12-15 07:36:55 -0800
    • Engine revision 3316dd8728
    • Dart version 2.18.6
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/tykan/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.11.3

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 70.0.4
    • Dart plugin version 221.6008.17

[✓] VS Code (version 1.71.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (1 available)
    • iPhone 14 Pro Max (mobile) • A66197AE-FB6B-45AC-93E8-82F1D3589B4F • ios • com.apple.CoreSimulator.SimRuntime.iOS-16-2 (simulator)

[✓] HTTP Host Availability
    • All required HTTP hosts are available
```
---
