### ISSUE TITLE
Android 무한 로딩

### ISSUE THREAD

**Issue by LSamjoo** [TykanN/kpostal#18]
0.5.1, 1.0.0-dev.1 두 버전 모두 사용해봤습니다.
사용 기기 : 삼성 갤럭시 S9 ( 안드로이드 10 ), S20 울트라, S21 ( 안드로이드 12 )
증상 : KpostalView 화면에 진입 한 후 화면을 못 불러 오고 무한 로딩에 들어갑니다.
디버그 모드에서는 정상 작동하고 있으며, 앱을 release 하여 사용하니 발생하고 있습니다.  

void runKopo(BuildContext context) async {
    Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) => KpostalView(callback: (Kpostal result) {
            setState(() {
              adressValue = result.address;
              jibunValue = result.jibunAddress;
              postCode = result.postCode;
              print('postal:$adressValue');
              print('jibunPostal:$jibunValue');
              if (jibunValue.isNotEmpty) {
                controllerAddress1.text = jibunValue;
              } else {
                controllerAddress1.text = adressValue;
              }
            });
          }),
        ));

현재 View 불러오는코드

**Comment by TykanN** [comment]
디버그 모드에서 정상 작동하나, 릴리즈 모드에서 로드가 안되는 경우 권한 문제일 가능성이 큽니다.

일반적으로 안드로이드 릴리즈 시 인터넷 권한을 포함하기 때문에
별도로 문서에 명시하지 않았습니다.

AndroidManifest.xml 파일에 하단 내용 추가해서 확인해보시길 바랍니다.
<uses-permission android:name="android.permission.INTERNET" />

추후 업데이트 때, 문서에도 기재하도록 하겠습니다.
감사합니다.
