### ISSUE TITLE
Geocoding 2.2.1 업데이트로 인한 이슈

### ISSUE THREAD

**Issue by dodri0605** [TykanN/kpostal#19]
[Geocoding 2.2.1 ](https://pub.dev/packages/geocoding/changelog#221)
- Updates documentation related to setting the locale.
- Added setLocaleIdentifier to the example app.
- Updates geocoding_ios version to 3.0.0.

---

Geocoding 2.2.1 이 업데이트 되면서, locationFromAddress 메소드의 파라미터 구성이 달라졌습니다.

```
/// geocoding.dart
Future<List<Location>> locationFromAddress(String address) =>
    GeocodingPlatform.instance!.locationFromAddress(
      address,
    );
```

이로 인해 kpostal_model.dart - searchLocation(String address) 메소드에서 에러가 발생합니다.
기존에 locationFromAddress() 메소드에 두번째 파라미터로 넣어주던 KpostalConst.localeKo 값은
GeoCoding 2.2.1 에서 새로 추가된 setLocaleIdentifier(KpostalConst.localeKo) 메소드로 추가하여 에러를 잡을 수 있었습니다.

```
/// kpostal_model.dart
  Future<List<Location>> searchLocation(String address) async {
    try {
      setLocaleIdentifier(KpostalConst.localeKo);
      final List<Location> result = await locationFromAddress(address);
      log('LatLng Found from "$address"', name: KpostalConst.packageName);
      return result;
    }
    ...
  }
```

Contribute 하는 방법을 모르는 주니어 개발자라.... 이렇게 글로라도 남기고 갑니다.

**Comment by dodri0605** [comment]
Geocoding 2.2.1 버전이 내려간건가요? 갑자기 2.2.0 으로 적용되어서 본 글에 쓴 내용으로 적용 안해도 될 듯 합니다.

![image](https://github.com/TykanN/kpostal/assets/90378963/15aa4cfd-5c67-4016-8eee-8682932dcea1)

분명 몇분 전까지만 해도 있었는데... 없어졌네요...

---

<img width="802" alt="image" src="https://github.com/TykanN/kpostal/assets/90378963/3a22402c-7fab-4cdf-b076-5c6ff9071e81">

쵤회 되었네용

**Comment by TykanN** [comment]
@dodri0605 
https://pub.dev/packages/geocoding/versions/2.2.1
현재 해당 버전이 철회된 것으로 확인되어서 다음 버전 출시까지 변경사항이 유지되는지 확인하고 대응하도록 하겠습니다!

제시해주신 해결법 좋은거 같습니다! 이참에 컨트리뷰트 해보시는게 어떨까요? ㅎㅎ
레포지토리 포크 하셔서 본인 레포지토리에서 작업하시고, PR 생성 시 작업하신 브랜치 선택하면 끝입니다!

**Comment by dodri0605** [comment]
아하! 포크로 가져와서 PR 보내면 되는거군여!
다음부터는 컨트리뷰트로 올려보겠습니다! ㅎㅎ
답변 해주셔서 감사합니다!!
