### ISSUE TITLE
좌표는 같이 받을 수 없을까요?

### ISSUE THREAD

**Issue by kwonsoonho** [TykanN/kpostal#2]
감사합니다!
잘 쓰고 있는데 혹시 
좌표는 같이 받을 수 없을까요?

**Comment by TykanN** [comment]
Kpostal은 무료로 제한 없이 사용 가능한 카카오 우편번호 서비스를 기반으로 제작되었습니다.
해당 서비스에서 주소의 좌표 값을 제공하지 않기 때문에 불가능합니다.
검색 후 해당 주소 기반으로 직접 다른 api를 이용해 경도, 위도 값을 찾으시면 됩니다.

https://apis.map.kakao.com/web/documentation/#services_Geocoder_addressSearch
이런 기능을 참고하시면 좋을 듯 합니다.

**Comment by kwonsoonho** [comment]
감사합니다!!

**Comment by TykanN** [comment]
@kwonsoonho  플랫폼에서 지원하는 지오코딩 서비스를 이용해서 주소 선택 시 경위도 좌표를 받을 수 있도록 업데이트 했습니다.
각각 latitude, longitude 프로퍼티로 값을 불러올 수 있습니다.
iOS랑 goolge docs를 보시면 아시겠지만 100% 신뢰성을 보장하지 않기 때문에, 안전 등과 관련된 목적에서는 권장하지 않습니다.
