### ISSUE TITLE
flutter_inappwebview, OrderedSet 에서 발생하는 Apple Privacy Manifest 미제공 문제

### ISSUE THREAD

**Issue by kimdindoo** [TykanN/kpostal#20]
<img width="681" alt="image" src="https://github.com/user-attachments/assets/4f23ed77-a145-48ff-acff-906449793835">

https://github.com/Weebly/OrderedSet/issues/41

<img width="734" alt="image" src="https://github.com/user-attachments/assets/1203fb4e-0737-48b5-beee-a24a3d71c3c3">

ios 배포 중 OrderedSet 패키지 Missing privacy manifest 이슈가 있어서 문의드립니다.
OrderedSet 패키지 5.0.0 -> 최신 버전으로 업그레이드 가능할까요?

**Comment by kimdindoo** [comment]
https://apnspush.com/privacy-manifest-sdks#all-86-required-sdks-and-status-in-supporting-privacy-manifest

flutter_inappwebview 패키지도 privacy manifest 응대가 안되어있는데, 혹시 다른 웹뷰(webview_flutter)로 바꾸실 의향도 있으신지 여쭤봅니다.

**Comment by TykanN** [comment]
@kimdindoo
안녕하세요!
flutter_inappwebview > OrderedSet 로 이어지는 SDK 의존성으로 발생하는 점 확인했습니다.

다만, flutter_inappwebview ios SDK 에서 Privacy Manifest 제공이 이루어지지 않은 이유로
Kpostal 패키지의 pub 공식 버전에서 웹뷰용 패키지를 갑작스럽게 교체하는 조치는 고려하고 있지 않는데요.

저는 공식 버전에서 큰 규모의 대응보다는 소스코드를 fork하여 수정하여 사용하거나 유저들이 자유롭게 수정 버전을 공유하여, 임시 수정하는 대응을 기대합니다. ( 오픈소스니까요 👍 ) 해당 수정 커밋은 언제든지 PR 가능하고, 적절한 시기에 병합/배포될 수 있습니다.

위 답변과 별개로, 제가 알기로는 개인정보 접근이 앱에서 사용하든, 앱이 사용하는 써드파티 패키지에서 사용하든 결국 최종적으로 모든 정보의 책임은 앱에 있는 것으로 알고 있습니다.
이로 인해 써드파티 SDK에서 PrivacyInfo.xcprivacy를 제공하지 않더라도 앱 수준에서 PrivacyInfo.xcprivacy를 제공하면 문제가 없는 것으로 알고 있습니다.

제가 해당 패키지를 사용하는 앱을 앱스토어에 배포하지 않아, 실제 앱스토어 심사 과정을 확인한 것은 아니라 **정확하지 않을 수 있습니다.**
해당 조치가 발표된 WWDC23 내용을 참고한 것입니다.

위 내용이 맞다면.. fork 보다는 앱에서 명시적으로 선언하시는게 가장 깔끔한 대응이라고 생각합니다.
만약 앱 수준에서 PrivacyInfo.xcprivacy 파일을 제공했을 때 문제가 없는게 관리하시는 앱을 통해 확인 가능하시다면 추가 답변 부탁드립니다.
틀렸다면 정정해놓도록 하겠습니다 :)

**Comment by TykanN** [comment]
덧붙여 flutter_inappwebview 패키지의 issue 가 많고, 대응이 매우 느린 점을 공감하고 있습니다.
장기적으로는 webview_flutter로 교체도 고려하고 있습니다.

당장 직접 변경하여 배포할 계획은 없습니다.
문제가 긴급하다면 이슈든 PR이든 많은 사용자들이 의견을 내어 주시리라 생각합니다.

많은 사용자들이 이슈를 확인하고 의견을 낼 수 있도록 닫지 않고 고정해두겠습니다!! 감사합니다

**Comment by kimdindoo** [comment]
@TykanN 
안녕하세요!

프로젝트 > ios > .symlinks / plugins > flutter_inappwebview_ios > ios 폴더 안에
Resources 폴더 생성 후 아래 와 같이 PrivacyInfo.xcprivacy 파일 생성


<img width="1190" alt="image" src="https://github.com/user-attachments/assets/66ada322-0507-4033-b572-a395a797cd7c">


```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyAccessedAPITypes</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array/>
	<key>NSPrivacyTracking</key>
	<false/>
</dict>
</plist>
```
PrivacyInfo.xcprivacy 파일에 위의 내용 입력

---

프로젝트 > ios > .symlinks / plugins > flutter_inappwebview_ios > ios > flutter_inappwebview_ios.podspec 파일  수정

<img width="836" alt="image" src="https://github.com/user-attachments/assets/7e6c08b8-34cc-48c1-98a7-f7c71fdbfa40">

```
  s.resource_bundles = {'flutter_inappwebview_ios_privacy' => ['Resources/PrivacyInfo.xcprivacy']}
```

```
s.platforms = { :ios => '12.0' }
s.dependency 'OrderedSet', '~>6.0.2'
```
---

위와 같은 방법으로 앱 배포에 성공하였습니다. 
좋은 패키지를 만들어주셔서 감사합니다.

**Comment by kimdindoo** [comment]
```jsx title="/src/components/HelloCodeTitle.js"
function HelloCodeTitle(props) {
  return <h1>Hello, {props.name}</h1>;
}
```

**Comment by TykanN** [comment]
`v1.1.0`로 배포되었습니다 👍 
https://pub.dev/packages/kpostal/versions/1.1.0
