### ISSUE TITLE
안드로이드 콜백이 안들어옵니다.

### ISSUE THREAD

**Issue by winprocsx** [TykanN/kpostal#4]
0.3.0 버젼 설치해서 사용하고 있는데요
'다솜1로200' 으로 검색해서 결과 클릭하면, 화면 전환이 되지 않고, 하얀화면 그대로 멈춰있습니다.
콜백이 안되는것 같습니다.

**Comment by TykanN** [comment]
안녕하세요.
경위도 데이터를 조회하면서 해당 주소에서 조회 값이 없어 나타나는 문제로 확인했습니다.

수정은 완료했지만, 최종 확인 후 내일 0.3.2버전으로 배포하도록 하겠습니다.

**Comment by winprocsx** [comment]
감사합니다!!! ㅎㅎ
좋은 모듈 만들어주셔서 감사드려요~
