### ISSUE TITLE
안드로이드 12에서 키보드가 안보여지는 오류가 발생합니다.

### ISSUE THREAD

**Issue by ghost** [TykanN/kpostal#5]
V/InputMethodManager( 1595): b/117267690: Display ID mismatch found. ViewRootImpl displayId=52 InputMethodManager displayId=0. Use the right InputMethodManager instance to avoid performance overhead.
V/InputMethodManager( 1595): java.lang.Throwable
V/InputMethodManager( 1595): 	at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:610)
V/InputMethodManager( 1595): 	at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1994)
V/InputMethodManager( 1595): 	at org.chromium.content.browser.input.ImeAdapterImpl.t(Unknown Source:20)
V/InputMethodManager( 1595): 	at org.chromium.content.browser.input.ImeAdapterImpl.updateState(Unknown Source:205)
V/InputMethodManager( 1595): 	at android.os.MessageQueue.nativePollOnce(Native Method)
V/InputMethodManager( 1595): 	at android.os.MessageQueue.next(MessageQueue.java:335)

왼쪽이 안드로이드 11 에뮬레이터, 오른쪽이 12 에뮬레이터 입니다.

왼쪽에는 오류없이 정상적으로 키보드가 보이지만, 오른쪽 12에서는 오류메시지가 뜨면서 키보드가 안보여집니다.

<img width="802" alt="스크린샷 2022-01-26 오후 4 14 30" src="https://user-images.githubusercontent.com/98448176/151119301-f724dfc8-fb61-434c-8750-64377d155404.png">

**Comment by TykanN** [comment]
Example 앱을 안드로이드12 에뮬레이터에서 확인했으나 문제가 확인되지 않습니다.
최소한의 reproducible code를 제시해주셔야 살펴 볼 수 있을 듯 합니다.

단순히 키보드 문제만을 봤을 때는 예상되는 원인
1. 안드로이드 hybrid-composition 웹뷰를 위해 그래들의 minSdkVersion 19 이상 필요
2. 에뮬레이터 기기의 설정 문제

실기기로 테스트 하는 것이 가장 정확한 방법입니다.

**Comment by cheonbrave** [comment]
저도 
갤럭시20+ 모델에서 kpostal 플러그인을 사용해서 오픈했을대 위 처럼 키보드가 발생하지 않는 현상이 
실제 사용자로부터 접수됐습니다~!! 

저희 경우
minSdkVersion 19
targetSdkVersion 31
이 설정으로 빌드되어있습니다
