### ISSUE TITLE
null safety이전 버젼에서도 작동하나요?

### ISSUE THREAD

**Issue by k0302** [TykanN/kpostal#6]
제가 null safety 나오기 이전 버전의 플러터와 kopo 를 사용해 앱을 만들었는데요, 어느샌가 kopo가 작동하지 않게 되었습니다ㅜ 그 앱에 이 kpostal을 kopo대신 대체해 넣으면 작동하게 되나요? 아니면 null safety 버젼으로 처음부터 다시 만들어야 하나요?

**Comment by TykanN** [comment]
null-safety 이후 패키지들은 다트 SDK 최소 2.12.0 버전 이상, 플러터 2.0 버전 이상을 요구합니다.
1 버전대의 플러터에서는 당연히 의존성 에러가 날 것으로 보입니다.

이전의 kopo 패키지와 작동 방식은 대부분 동일해서 기존 프로젝트만 null-safety 마이그레이션 하시면 큰 수정 없이 사용하실 수 있습니다.

처음부터 만들 필요는 없고, 마이그레이션 툴을 이용하면 생각보다 쉬운 과정이니 링크 참고해서 해보세요!
프로젝트를 지속하실 예정이라면 꾸준하게 의존하는 환경들은 업데이트 해주셔야 합니다.
https://dart.dev/null-safety/migration-guide
