### ISSUE TITLE
키보드 미발생 현상

### ISSUE THREAD

**Issue by cheonbrave** [TykanN/kpostal#8]
갤럭시20+ 모델에서
kpostal 플러그인을 사용해서 오픈했을대 
키보드가 발생하지 않는 현상이
실 사용자로부터 확인됐습니다

사용하는 Android 버전까지는 확인이 안됐지만

저의 경우
minSdkVersion 19
targetSdkVersion 31
이 설정으로 빌드되어있음에도
키보드 발생이 안되며, 영상 자료도 있습니다

KpostalView 를 사용한 코딩내용은 example 소스랑 동일해서 딱히 특히한점은 없습니다 ㅠ

**Comment by cheonbrave** [comment]
Uploading FullSizeRender.MOV…

**Comment by TykanN** [comment]
@cheonbrave 
안녕하세요.

플러터의 웹뷰 키보드 문제로 알려진 이슈들이 많은데
안드로이드에서 Hybrid Composition 방식으로 웹뷰를 그리면서 해결된 것으로 알고 있습니다.

현재 Kpostal 패키지도 하이브리드 컴포지션 방식의 웹뷰를 사용하고 있습니다.
패키지 내의 example을 빌드하여 안드로이드 시뮬레이터(안드로이드 12 버전), 실기기(갤럭시 s21, 안드로이드12)로 확인해본 결과,
정상적으로 작동하여 해당 증상을 reproduce 하지 못했습니다.

버그 수정은 개발자가 repoducible code를 확인 가능해야 하는데, 증상 설명 만으로는 해결법이 없습니다.
제가 테스트한 앱 코드는 패키지 내 example 프로젝트이며, flutter 2.8.1 버전입니다.
테스트 디바이스는 위에서 말씀드린 시뮬레이터, 실기기 2종 입니다.

문제가 발생하는 기기에서 동일하게 example 프로젝트를 빌드해서 확인해보시고 코멘트 부탁드립니다.

**Comment by cheonbrave** [comment]
피드백 감사합니다 

테스트하신 버전은 kpostal 0.4.0 인가요 ? 
저는 kpostal 0.3.2  버전입니다 

한번 0.4.0 으로 업그레이드해서 테스트 해보겠습니다

**Comment by TykanN** [comment]
네, 0.4.0 버전으로 테스트 부탁드립니다.

**Comment by cheonbrave** [comment]
안드로이드 12 버전 에뮬레이터에서
kpostal 0.3.2 버전으로 테스트 했을때 키보드가 발생하지 않았구요

kpostal 0.4.0 으로 업그레이드 후 테스트 해보니 키보드가 잘 나옵니다
버전업으로 해결됐습니다
