### ISSUE TITLE
안드로이드 콜백 관련입니다.

### ISSUE THREAD

**Issue by choi3179** [TykanN/kpostal#9]
가장 최근에 올라온 0.4.1 버전 사용중입니다.

검색결과 클릭 후 콜백으로 넘어가지 않고 하얀 화면에서 멈추는 현상이 발생하고 있습니다.

모든 스마트폰에서 발생하는 현상은 아니고 일부 기종에서만 발생하는 오류인 것 같습니다.

제가 테스트한 스마트폰은 갤럭시노트8 안드로이드9 버전입니다.

-- 안드로이드8 버전에서도 같은 현상이 확인되어 안드로이드10 이하 버전에서 발생하는 문제라고 생각됩니다.

**Comment by yakppal** [comment]
저도 안드로이드 10에서 하얀 화면에서 멈추는 현상 재현 됩니다.

**Comment by yakppal** [comment]
안드로이드 10에서도 하얀 화면에서 멈추는 현상 재현 됩니다.
